### ISSUE TITLE
v8 api deprecation 

### ISSUE THREAD

**Issue by Stvad** [jason0x43/go-toggl#15]
v8 is getting deprecated soon https://developers.track.toggl.com/changes/2022/10/01/api-v8-deprecation it'd be great to support v9 (coming here from Alfred workflow, which presumably will stop working on April 1st)

**Comment by jjarava** [comment]
FYI, @Stvad -- I created an issue on the [Alfred-toggl](https://github.com/jason0x43/alfred-toggl) project: https://github.com/jason0x43/alfred-toggl/issues/65 and [@s7anley](https://github.com/s7anley) mentioned he was looking into it.

**Comment by Stvad** [comment]
#17
